data:
  num_workers: 2

  data_dir: "data/processed"
  raw_dir: "data/raw/physionet.org/files/ptb-xl/1.0.1/"

  features: ['sex', 'age', 'height', 'weight']

  sampling_rate: 100

  pathologies: ["SARRH", "SBRAD", "STACH", "AFIB"]
