# conf/data.yaml
data:
  # Общие параметры
  batch_size: 256
  epochs: 15
  num_workers: 2

  # Путь к данным
  data_dir: "data/processed"
  raw_dir: "data/raw/physionet.org/files/ptb-xl/1.0.1/"

  # Разделение на train/valid
  val_part: 0.2

